### ISSUE TITLE
Plugin compatibility issue with Perfect Woocommerce brands plugin

### ISSUE THREAD

**Issue by peeyooshk** [10up/ElasticPress#1588]
**Describe the bug**

When using with Perfect Woocommerce brands plugins, the brand pages show products from all brands instead of showing from the selected bran alone.
**Steps to Reproduce**

1. Go to '...' Brand page
2. Click on '....' Any brand
4. See error You would see products from all brands instead of the selected brand.

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - Plugins and version: 
 - Theme and version: 
 - Other installed plugin(s) and version(s):

**Additional context**

**Comment by wss-chadical** [comment]
@peeyooshk Fyi - this same behavior is happening for us using the [Woocommerce Brands](https://docs.woocommerce.com/document/wc-brands/) plugins as well. Of course - only happens when EP indexing for Protected Content is enabled.

This happens using ES 5.4 (EP master) and ES 7.4 (EP develop)

The question here is:
How do I configure ES to search on Woocommerce Brands?

All brands in the WC plugin are standard Taxonomies....

**Comment by tlovett1** [comment]
Should be fixed in #1617

**Comment by peeyooshk** [comment]
I tested with the plugin version 3.3 and the issue persists.

**Comment by peeyooshk** [comment]
Just to mention i used Amazon elastic search 7.1.

**Comment by brandwaffle** [comment]
@peeyooshk can you test with the develop branch? This fix is not present in 3.3. Thanks!

**Comment by roditi3811** [comment]
I have this error also with EP v3.3, ES 7.5.2 and YITH WooCommerce Brands Add-on Premium
Any updates on the fix?
Thanks!

**Comment by peeyooshk** [comment]
> @peeyooshk can you test with the develop branch? This fix is not present in 3.3. Thanks!

It works fine with the develop branch. By when is the implementation in main plugin happening so could update the same at that time to ensure to be on same patch level.

**Comment by roditi3811** [comment]
Yup, I can confirm that the brands are working correct now. 
Initially I was using the version from Wordpress plugins, but now I installed the developer version from github, and works perfect.
Thanks!
