### ISSUE TITLE
Compatibility issue with plugin Woocommerce Brands.

### ISSUE THREAD

**Issue by websuperhero** [10up/ElasticPress#1611]
Hello, 

I found that Woocommerce Brands plugin (Official WooCommerce plugin, https://docs.woocommerce.com/document/wc-brands/?_ga=2.150949310.920091466.1578403700-2130342966.1566608674 ) conflicts with the ElasticPress. 
The Woocomerce Brands plugin doesn't show results of any brands filters when the ElasticPress is active. 

Wordpress version: 5.3.2
ElasticPress version: 3.3
WP Theme: Flatsome version 3.10.1
Browser: Chrome

**Comment by brandwaffle** [comment]
@websuperhero thanks for the report, we will take a look shortly! Can you confirm that you ran a full reindex of ElasticPress after activating the Brands plugin? If not, can you try that as well?

**Comment by websuperhero** [comment]
@brandwaffle I have reindex the ElasticPress many many times because I tried many times to find a solution and for troubleshooting purposes.

**Comment by brandwaffle** [comment]
@websuperhero That's what I suspected 😄 

We'll dig in and update this ticket as soon as we learn more!

**Comment by tlovett1** [comment]
#1617 should fix this.

**Comment by websuperhero** [comment]
@tlovett1 Hello again. Today I installed the developer version of EP from your repo. The issue with Woocommerce Brands plugin still persists. Any fix please?

**Comment by slaxxarn** [comment]
@tlovett1  Will bump this, the issue is in Facet.php and row 326 - 333. You add a tax query with field = slug and operator = AND / OR

While woocommerce brand adds/uses term_id as field and IN as operator if you use their own widget

```php
foreach ( $selected_filters['taxonomies'] as $taxonomy => $filter ) {
	$tax_query[] = [
		'taxonomy' => isset( $attribute_taxonomies[ $taxonomy ] ) ? $attribute_taxonomies[ $taxonomy ] : $taxonomy,
		'field'    => 'slug',
		'terms'    => array_keys( $filter['terms'] ),
		'operator' => ( 'any' === $settings['match_type'] ) ? 'or' : 'and',
	];
}
```
