### ISSUE TITLE
BUG: The settings page looks messy

### ISSUE THREAD

**Issue by dertuxmalwieder** [10up/ElasticPress#2260]
**Describe the bug**
I'm positive :-) that this is not how it is supposed to look. Anyway, it has for a long time now, in almost all of my browsers (including Safari and Vivaldi). I always use the latest ElasticPress version, but the bug has been there for as long as I even *use* it (which is more than a year).

All other ElasticPress pages look just fine.

**Screenshots**
<img width="1678" alt="Bildschirmfoto 2021-07-08 um 14 51 24" src="https://user-images.githubusercontent.com/125629/124924925-3b9f9980-dffc-11eb-9717-685b60102731.png">

**Comment by felipeelia** [comment]
Hi @dertuxmalwieder, definitely that is not how it is supposed to look! Do you see any errors in your browser's console? Also, we've released a new version yesterday, do you see that same problem with it? Thanks in advance.

**Comment by dertuxmalwieder** [comment]
Yes, I updated just five minutes ago and the error is still there. No, the JS console is surprisingly empty.

**Comment by mikelking** [comment]
@dertuxmalwieder 

- Out of curiosity do you have a staging site where you can replicate this? 
- Have you tried turning off all plugins to isolate and eliminate any CSS interference?
- Although it's rare the theme could also cause weirdness in the CMS backend.

**Comment by felipeelia** [comment]
Hm, that is interesting. Can you please check:
1. If you do have the wp-content/plugins/elasticpress/dist/css/dashboard-styles.min.css file in your server and if that has the correct permissions and
2. If that file is called in the HTML of that page.

**Comment by dertuxmalwieder** [comment]
> * Out of curiosity do you have a staging site where you can replicate this?

Sadly, no. This is my personal blog which does not need any DevOps... :-)

> * Have you tried turning off all plugins to isolate and eliminate any CSS interference?

Not yet. I would suspect a caching issue as of now, but I don't have any elaborated caching enabled anyway. (I try to keep the list of active plug-ins short.)

> * Although it's rare the theme could also cause weirdness in the CMS backend.

The theme is mostly mine by now, but I also used different themes (I have, for example, an April Fools theme).

------

> 1. If you do have the wp-content/plugins/elasticpress/dist/css/dashboard-styles.min.css file in your server and if that has the correct permissions

It's there and it has `-rw-r--r--`.

> 2. If that file is called in the HTML of that page.

Yup.

<img width="1678" alt="Bildschirmfoto 2021-07-08 um 15 04 32" src="https://user-images.githubusercontent.com/125629/124926504-e49ac400-dffd-11eb-9292-336ac466f4ea.png">

**Comment by felipeelia** [comment]
That could mean a plugin (normal or mu-plugin) is overriding something on CSS or HTML, @dertuxmalwieder. I'd recommend you to install the [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) plugin and with its Troubleshooting mode disable ALL other plugins and use a default theme (the good thing about this plugin is that it'll affect only your own user, the others will see the site as usual).
Also, did you already look at the "elements" tab to see why the style is not applied to the elements on the page?

**Comment by dertuxmalwieder** [comment]
> Also, did you already look at the "elements" tab to see why the style is not applied to the elements on the page?

Yup - and it actually is! (Most of the styles come from either the browser, said CSS file or `load-styles.php` which is a part of WordPress itself.) So there is no "override" here in my opinion.

*Anyway*, I installed said plugin (which I did not know yet - thank you, it is really handy for my own plugin development!), disabled everything but ElasticPress and it still looked like the screenshot I posted earlier. **But** , surprisingly, enabling Twenty Twenty fixed the problem!

Interesting.

Now how can I fix that *in my theme*?

**Comment by mikelking** [comment]
@dertuxmalwieder 

After you solve this you may want to look at https://localwp.com/. I know it's a WP Engine product but you do not need to use it with their hosting to setup a local mirror of your site. Having a not production environment where you can turn everything off to suss out issues like this is really helpful.

**Comment by dertuxmalwieder** [comment]
> Having a not production environment where you can turn everything off to suss out issues like this is really helpful.

I admit that I've been toying with the Zola SSG for a while which would have the advantage that I'd *always* have a local environment. Sadly, WordPress does many things quite well right now...

**Comment by felipeelia** [comment]
> Now how can I fix that in my theme?

That is hard to tell @dertuxmalwieder. Before figuring out how to fix it, obviously, you'd need to figure out _why_ it is breaking / not applying the correct CSS. You should have a div with class `wrap` there, is that okay? ElasticPress renders some elements with the `.ep-feature` class, is that happening? Worst case scenario you'll need to create a local env and start removing things from your theme until it works.

As it is something specific to your theme, I'm going ahead and closing the issue but if you have the chance to figure out why and let us know, that would be great. Thanks in advance!

**Comment by dertuxmalwieder** [comment]
> You should have a div with class `wrap` there, is that okay?

Yup.

> ElasticPress renders some elements with the `.ep-feature` class, is that happening? 

No. That could be the culprit. But there is nothing in my PHP files that would remove that. 🤨

`.ep-features` still exists though.
