### ISSUE TITLE
BUG: Version 4.3.0 release notes link to Facet By Meta plugin

### ISSUE THREAD

**Issue by jonasborneland** [10up/ElasticPress#3094]
**Describe the bug**

4.3.0 notes this deat link: [this plugin](https://raw.githubusercontent.com/10up/ElasticPress/develop/tests/cypress/wordpress-files/test-plugins/elasticpress-facet-by-meta.php)

Im using 4.3.1 and I can't see the Facet By Meta anywhere in widgets? Where do I find it? Do I need the plugin mentioned above? :)

**Steps to Reproduce**

1. Go to 'https://github.com/10up/ElasticPress/releases'
2. Click on 'the link in 4.3.0'

**Comment by felipeelia** [comment]
Hey @jonasborneland, thanks for the heads up! I've just fixed the link now, do you mind trying again? And yeah, you will need that plugin in order to see the Facet By Meta block in the dashboard.

**Comment by jonasborneland** [comment]
@felipeelia Thank you for the quick reply! I have installed and activated the plugin, but I still don't see the Facet By Meta block in the widget area?

**Comment by felipeelia** [comment]
Hey @jonasborneland, are you using the Classic Editor plugin or something similar? Currently, the new Facet by Meta is only available as a block, so you need to be using the new Block Editor to manage the widget areas.

**Comment by jonasborneland** [comment]
Hi @felipeelia yes! that was it. It's working now without the classic editor 😊
I'm trying to use a metafield which contains serialized data. Right now the Facet by Meta output is like:
```
a:2:{i:0;s:3:"110";i:1;s:3:"116";}
a:2:{i:0;s:3:"122";i:1;s:3:"128";}
a:2:{i:0;i:68;i:1;i:74;}
a:2:{i:0;i:80;i:1;i:86;}
a:1:{i:15;s:3:"134";}
a:2:{i:0;i:74;i:1;i:80;}
a:3:{i:6;s:2:"80";i:7;s:2:"86";i:8;s:2:"92";}
a:2:{i:6;s:2:"80";i:7;s:2:"86";}
a:4:{i:9;s:2:"98";i:10;s:3:"104";i:11;s:3:"110";i:12;s:3:"116";}
a:4:{i:11;s:3:"110";i:12;s:3:"116";i:13;s:3:"122";i:14;s:3:"128";}
a:1:{i:0;s:2:"44";}
a:2:{i:0;i:104;i:1;i:110;}
```

Any clue on how to make it work? Is there a hook to change it maybe before indexing?

Here is how it should be working:
In the edit area of my WC product, theres some meta fields with checkboxes to choose which clothing-sizes the product is matching:
[x] size 110    [x] size 116    [o] size 122    [o] size 126

In the top of this message, this line: a:2:{i:0;s:3:"110";i:1;s:3:"116";}
is telling that the product match size 110 and size 116.

The Facet by Meta output should be listing just a list of sizes, and when you click on one size, it should show products which is matching the size.
So the Facet by Meta output should just be showing like:
110
116
122
128

I hope it makes sense to you, and you could help me with a clue on which hooks to use to archive this? 😊 Thanks a lot for your help!
