### ISSUE TITLE
Issue with Polylang plugin and localized home pages showing error 404 when ElasticPress activated

### ISSUE THREAD

**Issue by fidjius** [10up/ElasticPress#640]
Hello,
I am using Wordpress 4.6.1 with Polylang plugin version 2.0.9. 
I just installed ElasticPress version 2.1.2 and I meeting an issue with all the localized home pages which now are displaying an 404 error : https://mydomain/fr/ or https://mydomain/en/ etc...
When I deactivate ElasticPress, my home pages are displaying well again.
Could you please check this? Thank you in advance.
Best regards

**Comment by Ritesh-patel** [comment]
Hi @fidjius 

I checked with Polylang plugin activated, added a new page but with ElasticPress active, it's working fine for me. Can you try refreshing permalinks if this issue occurs?

Regards,
Ritesh

**Comment by fidjius** [comment]
Hi

The issue just occurs for the localized frontpages, not for the other pages of the website. In the Polylang settings, this setting is checked : "The front page url contains the language code instead of the page name or page id".
See screenshot attached.
Best regards

![2016-11-23-12_35_50-languages-wordpress](https://cloud.githubusercontent.com/assets/334505/20560576/5ce2d540-b17a-11e6-9204-4911e428bec0.png)

**Comment by Ritesh-patel** [comment]
Hi @fidjius 

Thanks for the details. As per our findings, this issue only exist if WooCommerce module is active. We are looking into it and will have fix ready for it.

Regards,
Ritesh

**Comment by Ritesh-patel** [comment]
Closing this as it has been fixed in #642.

**Comment by fidjius** [comment]
Sorry, but this issue is not fixed. I still have the same issue.

**Comment by wordpresser12345** [comment]
same for me @fidjius - it's not fixed... can anyone help?

**Comment by tre-SKA** [comment]
I have the same problem.

**Comment by agriboed** [comment]
Hey there!

@wordpresser12345 @fidjius 
Are you using "Wordpress 2-Step Verification" plugin?
