### ISSUE TITLE
If a user tries to WP-CLI sync during dashboard sync they are not prevented

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#713]
I did try:
1. Sync in dashboard and then run index from wpcli. It doesn't prevent
2. Run index from wpcli and then Sync in dashboard. It doesn't prevent
3. Sync in dashboard in 2 different browser. It doesn't prevent 
4. Run index from wpcli in different terminal. It doesn't prevent 

Environment:
WP 4.7.2
EP 2.2
ES 5.0.0

**Comment by tlovett1** [comment]
This was something that @Ritesh-patel fixed I thought.

**Comment by tlovett1** [comment]
@ivankristianto can you test this one with the fix I pushed?

**Comment by ivankristianto** [comment]
I test it and the wpcli indexing still not prevent the dashboard sync.
Here is the video capture:
https://www.youtube.com/watch?v=jfgMiyq0Z8k&feature=youtu.be

**Comment by tlovett1** [comment]
Can you debug a fix?

**Comment by ivankristianto** [comment]
Yes sure
